name: App Portal Build

on:
  push:
    branches-ignore:
      - 'release/**'

env:
  buildConfiguration: Release

permissions:
  pull-requests: write  # required by sticky-pull-request-comment@v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet cake --task=restore

      - name: Build solution - ${{ env.buildConfiguration }}
        run: dotnet cake --task=build --configuration=${{ env.buildConfiguration }} --exclusive

      - name: Run unit tests - ${{ env.buildConfiguration }}
        run: dotnet cake --task=unit-tests --configuration=${{ env.buildConfiguration }} --exclusive

      - name: Run integration tests - ${{ env.buildConfiguration }}
        run: dotnet cake --task=integration-tests --configuration=${{ env.buildConfiguration }} --exclusive

      - name: Run acceptance tests - ${{ env.buildConfiguration }}
        run: dotnet cake --task=acceptance-tests --configuration=${{ env.buildConfiguration }} --exclusive

      - name: Generate test reports
        run: dotnet cake --task=test-reports --exclusive

      - name: Upload test reports
        run: dotnet cake --task=upload-test-reports --exclusive

      - name: Generate code coverage reports
        run: dotnet cake --task=code-coverage-reports --exclusive

      - name: Upload code coverage reports
        run: dotnet cake --task=upload-code-coverage-reports --exclusive

      - name: Find the PR associated with this push
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Add test reports PR Comment on Github
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: testReports
          hide: true
          hide_classify: "OUTDATED"
          number: ${{ steps.findPr.outputs.pr }}
          path: ./artifacts/tests/dbml.NET.test_report.md

      - name: Add code coverage reports PR Comment on Github
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: codeCoverageReports
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          number: ${{ steps.findPr.outputs.pr }}
          path: ./artifacts/coverage/SummaryGithub.md
